### ISSUE TITLE
Improper error highlighting

### ISSUE THREAD

**Issue by salmanmuzammil** [Harry-Hopkinson/vim-vscode-theme#15]
# Problem: 
The extension does not highlight errors in python, maybe in other languages as well but I only saw this in python so idk

let's say I have missed some enum names: 
I missed the E at the end the normal default Dark+ will show this as
![Dark+ error highlight](https://user-images.githubusercontent.com/98395146/210070953-c516a1e3-2a57-4ad8-a1b9-782a8289f2ad.png)

It's obvious from the color that I made a typo

but in the vscode vim theme ext there is no difference:
![image](https://user-images.githubusercontent.com/98395146/210071049-3e1c50ca-1a31-4e42-ba6f-64d7ce364af7.png)

**Comment by Harry-Hopkinson** [comment]
Is that an error? There is no red syntax highlighting.

**Comment by Harry-Hopkinson** [comment]
Do you have a python server running on vscode?

**Comment by fla-t** [comment]
Sorry for the late reply, but yes I have Pylance running on vscode. I think I have might have the swigglys turned off but i usually rely on the color change and it.

my problem is why isnt the theme not handling it like the default theme and other themes

**Comment by Harry-Hopkinson** [comment]
No problem, that is strange I am not sure why there is no highlighting showcasing the error. The extension highlights the value property, all apart from the typo. So maybe one can use that for error messages?

**Comment by fla-t** [comment]
Yeah, turns out pylance wasnt on when mypy was on. I turned mypy off now i am getting accurate red swigglys on the above mentioned error.

I will spend this weekend checking if i can make this better by tweaking the repo.
