### ISSUE TITLE
Margin line numbers color

### ISSUE THREAD

**Issue by ChristopheDassise** [Harry-Hopkinson/vim-vscode-theme#33]
Hello,

I use your theme, and like it.
However, is it possible to set the color of the line numbers in the editor margin a little more lighter to increase readibility of them ?

Thank's for your answer.

**Comment by Harry-Hopkinson** [comment]
For which colour theme? Or for all of them?

**Comment by ChristopheDassise** [comment]
Hello,

My proposition is for the dark themes (I don't use any light theme)
