### ISSUE TITLE
Sticky pane blends in with the rest of the code when sticky scroll is enabled

### ISSUE THREAD

**Issue by yay** [Harry-Hopkinson/vim-vscode-theme#35]
Hi,

I've looked at many solarized themes but the one from this bundle is the closest to perfect IMO :)

One very minor thing is that when sticky scroll is enabled:
<img width="524" alt="Screenshot 2024-09-14 at 6 03 27 PM" src="https://github.com/user-attachments/assets/6d84e0f8-89d3-4fd5-9f5f-d01acc83abb6">

The sticky pane blends in with the rest of the code, which can create confusion:
<img width="424" alt="Screenshot 2024-09-14 at 6 04 43 PM" src="https://github.com/user-attachments/assets/2b41ad2d-5b03-43e7-af80-1d5f36d7a1bd">

Would it be possible to have some kind of subtle shadow or a separator to easily tell where the pane ends and code begins? For example:
<img width="871" alt="Screenshot 2024-09-14 at 6 05 16 PM" src="https://github.com/user-attachments/assets/95ba2025-720b-40ae-96bc-590134005bdc">

Would it also be possible to tweak the highlight background color within the sticky pane to have a bit less contrast? Current looks is as follows:
<img width="907" alt="Screenshot 2024-09-14 at 6 12 58 PM" src="https://github.com/user-attachments/assets/d786c3a9-2a88-4d93-a400-7386ec02159c">

Whereas current line highlight in the rest of the code is much more subtle:
<img width="562" alt="Screenshot 2024-09-14 at 6 13 39 PM" src="https://github.com/user-attachments/assets/26f0e28e-9545-4f2f-8859-e051ae8d0641">

**Comment by Harry-Hopkinson** [comment]
I have opened a Pull Request addressing the requested changes.
