### ISSUE TITLE
Is there this theme for nvim?

### ISSUE THREAD

**Issue by gabrielforster** [Harry-Hopkinson/vim-vscode-theme#37]
I know that this is inspired by Gruvbox theme... But is there a version of this exactly themes for nvim/vim? Especially "Vim Dark Medium". Every version of Gruvbox I've installed has no such colors as yours.

--- 
![image](https://github.com/user-attachments/assets/e9841a73-4ea4-4999-b460-6f64174151a9)

**Comment by Harry-Hopkinson** [comment]
This was originally a port of the [Gruvbox colour scheme](https://github.com/morhetz/gruvbox) for vim. But then over time I added more themes like solarized and a [deep dark port](https://github.com/challenger-deep-theme/vim)

**Comment by Harry-Hopkinson** [comment]
I have not yet created a theme for nvim but may in the future!

**Comment by gabrielforster** [comment]
I would be really appreciated.
Thanks for the answer.

**Comment by Harry-Hopkinson** [comment]
I will look at porting the themes in the future.
